In [1]:
import numpy as np
import time

In [2]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
c = 0

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print(c)
print("For loop:" + str(1000*(toc - tic)) + "ms")

249941.58693196214
Vectorized version:22.241830825805664ms
249941.58693196892
For loop:329.1480541229248ms


In [3]:
A = np.array([[56.0, 0.0, 4.4, 68.0], [1.2, 104.0, 52.0, 8.0], [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = np.sum(A, 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = 100 * A / cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
